quit modal
pdybowski/village-defense pull request #123
Opened 2021-02-07 20:01 UTC by hoolek77

2021-02-08 11:45 UTC, pdybowski requested changes
![image](https://user-images.githubusercontent.com/38506213/107215414-90b68f80-6a0b-11eb-953a-ef2759a79a37.png)

2021-02-08 19:13 UTC, pdybowski reviewed
also please add: align-self: center to .quit-button
and remove blue outline when focus
![image](https://user-images.githubusercontent.com/38506213/107269541-0a6d6e00-6a4a-11eb-9de4-08c0f89482be.png)

2021-02-08 19:13 UTC, pdybowski commented on src/app/game.ts
>        window.clearInterval(this.intervalId!)
we dont need '!' at the end of intervalId. We already checked if its not udefined. we could actually get rid of if statement and then we can have this.intervalId! 
Im not even sure that we still need "!". it wont throw an error there if intervalId is undefined

2021-02-08 19:13 UTC, pdybowski commented on src/app/components/quitModal.ts
> +import { GamePage } from '../screens/index'
just ../screens
it will automatically search for index.ts in this directory

2021-02-08 19:13 UTC, pdybowski commented on src/app/components/quitModal.ts
> +    const popupBtn = document.querySelector('.popup__close-btn') as HTMLElement
its button. use HTMLButtonElement

2021-02-08 19:13 UTC, pdybowski commented on src/app/components/quitModal.ts
> +  private quitYesBtn: HTMLElement
HTMLButtonElement - should work

2021-02-09 12:58 UTC, pdybowski approved these changes

2021-02-09 12:58 UTC, pdybowski commented on src/app/game.ts
> +    if (this.isGamePaused == true) return
You can do it without comparison

2021-02-10 10:54 UTC, bartoszbialecki approved these changes

2021-02-10 11:15 UTC, merged