redo popup render method
pdybowski/village-defense pull request #134
Opened 2021-02-10 16:14 UTC by ibednorz

2021-02-11 22:46 UTC, pdybowski requested changes
Also please make sure that close game modal is up to date. I guess we build additional button there in the old way. Change if please

2021-02-11 22:46 UTC, pdybowski commented on src/app/components/popup.ts
> +  additionalBtn?:string,
You can actually set new optional Object additiinalBtn with properties such as classes value, styles etc

2021-02-12 10:01 UTC, pdybowski commented
Dodatkowe komentarze 

![image](https://user-images.githubusercontent.com/38506213/107754193-6de4ed80-6d21-11eb-9f11-a32fc45fe278.png)
![image](https://user-images.githubusercontent.com/38506213/107754298-90770680-6d21-11eb-8a01-9f4bf84280e8.png)

2021-02-12 14:04 UTC, pdybowski approved these changes

2021-02-12 17:10 UTC, hoolek77 approved these changes

2021-02-12 17:10 UTC, merged