add copyplugin that copies music
pdybowski/village-defense pull request #135
Opened 2021-02-10 17:39 UTC by ibednorz

2021-02-10 17:55 UTC, pdybowski requested changes
We also need to have audio files in our dist file because our code have different path to get audio then /assets/audio. Please add const music_name = require('path') in files where we use audio

2021-02-11 22:43 UTC, pdybowski requested changes

2021-02-11 22:43 UTC, pdybowski commented on src/app/components/battle.ts
> +const battle = require('../../assets/audio/battle.mp3')
Rename it to battle_music

2021-02-11 22:43 UTC, pdybowski commented on src/app/components/battle.ts
> +const music = require('../../assets/audio/music.mp3')
Rename it to main_music or deafult_music

2021-02-11 22:43 UTC, pdybowski commented on webpack.common.js
> +        { from: "src/assets/audio", to: "" }
I think we don't need that.when we have require(something) in scripts then webpack pack music in the dist directory

2021-02-12 11:28 UTC, hoolek77 approved these changes

2021-02-12 16:54 UTC, pdybowski approved these changes

2021-02-12 16:54 UTC, merged