Music background #12
pdybowski/village-defense pull request #31
Opened 2021-01-24 14:09 UTC by aleksandraj036

2021-01-24 15:53 UTC, hoolek77 requested changes

2021-01-24 15:53 UTC, hoolek77 commented on src/app/utils/audio.ts
> +    audio.volume = 0.7;
There's an error. You don't specify type of audio variable. You can fix it by adding 'as HTMLAudioElement' at the end of line 2.

2021-01-24 15:53 UTC, hoolek77 commented on .vscode/settings.json
> +}
You should remove this file and directory and next time start the application by command 'npm start'

2021-01-24 17:41 UTC, pdybowski requested changes
Small changes

2021-01-24 17:41 UTC, pdybowski commented on src/app/index.ts
> +export * from './utils/audio'
Change it just to './utils'
In utils/index.ts add export * from './audio'

2021-01-24 17:41 UTC, pdybowski commented on src/app/index.ts
> +aj-12
It will cause an error. Probably undefined variable

2021-01-24 17:41 UTC, pdybowski commented on src/app/index.ts
> +master
It will cause an error

2021-01-24 17:41 UTC, pdybowski commented on src/app/utils/audio.ts
> +export const music = document.addEventListener("DOMContentLoaded", event => {
Okay, this one is bigger. Change it to a function - playAudio(volume) and import it in app.ts file. Run this method in App.start(). Volume argument should be used to init vaudio volume. Let's say default value in app.ts should be set to 0.7
Remove event listener in that file. App.start() is triggered inside this event. Moreover you can add new method in audio.ts file such as audioSettings(volume). Then in the body of this function run playAudio(volume)

2021-01-24 17:41 UTC, pdybowski commented on src/app/utils/audio.ts
> +    audio.volume = 0.7;
Audio.volume = volume ?? 0.7

2021-01-24 19:54 UTC, pdybowski requested changes
Jeszcze cos 🤓

2021-01-24 19:54 UTC, pdybowski commented on src/app/app.ts
> +  audioSettings() {};
One line up - inside start()

2021-01-24 19:54 UTC, pdybowski commented on webpack.common.js
> +        test: /\.mp3$/,
Move this regex to test where png,jpg etc are 
You don't need to specify the same loader twice

2021-01-24 22:50 UTC, pdybowski requested changes

2021-01-24 22:50 UTC, pdybowski commented on src/app/utils/audio.ts
> +export const playAudio = function(volume: number) {
Run this function inside App Class, inside start() method. Below console.log(Starting application...),
Set argument value to 0.7

2021-01-24 22:50 UTC, pdybowski commented on src/app/app.ts
> +import {audioSettings} from './utils'
nah, sent you image on discord

2021-01-25 13:32 UTC, pdybowski approved these changes

2021-01-25 13:40 UTC, hoolek77 approved these changes

2021-01-25 14:27 UTC, bartoszbialecki approved these changes

2021-01-25 17:24 UTC, merged