Homepage UI improvements
pdybowski/village-defense pull request #40
Opened 2021-01-26 16:07 UTC by GoraJakub

Please review

# Homepage startscreen
![image](https://user-images.githubusercontent.com/74857860/105869210-47bc0f80-5ff7-11eb-89ec-33cd1a2faa94.png)

# Button hover
![image](https://user-images.githubusercontent.com/74857860/105869393-7b973500-5ff7-11eb-9300-6d616670aba0.png)

# Dropdown list + hover
![image](https://user-images.githubusercontent.com/74857860/105869751-dd579f00-5ff7-11eb-898f-f87732b93531.png)

# People 
![image](https://user-images.githubusercontent.com/74857860/105870708-d1b8a800-5ff8-11eb-922e-1f2e288bd689.png)

# Dwarfs
![image](https://user-images.githubusercontent.com/74857860/105870752-de3d0080-5ff8-11eb-9e1d-90ddbff35691.png)

2021-01-26 19:17 UTC, pdybowski requested changes
Change button border bottom color when hover E.g. to dark green but not too dark.
Remove box shadow from drop down list or just leave border shadow (remove shadow between options). Also add something to highlight current option. So when people are selected and you open drop down "People" (box on the very top) should look different then other options in drop down

2021-01-26 19:17 UTC, pdybowski commented on src/app/app.ts
> -    const gamepage = new GamePage()
Restore it. We need this game page for tests for now

2021-01-26 19:19 UTC, pdybowski commented
Moreover you can change background color from green to gray when dwarfs are picked and to yellow or some other color that is associated to the people's image when people class is selected

2021-01-26 22:32 UTC, pdybowski requested changes
remove people.jpg, dwarfs.jpg, elfs.jpg

2021-01-26 22:32 UTC, pdybowski commented on src/app/screens/homepage/index.ts
> +    this.characterButtonOptions.forEach((e) => {
e is associated with events. you can pass opt or option instead of e

2021-01-26 22:32 UTC, pdybowski commented on src/index.html
> +      href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap"
take this content and place it in assets/fonts/google-fonts.css file

2021-01-26 22:32 UTC, pdybowski commented on src/index.html
> +      <source src="assets/audio/music.mp3" type="audio/mpeg" />
we dont need this '/' at the end

2021-01-26 22:32 UTC, pdybowski commented on src/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com" />
we dont need it here

2021-01-27 00:19 UTC, GoraJakub commented
# NEW PHOTOS

## Button hover
![image](https://user-images.githubusercontent.com/74857860/105923835-457ca400-603d-11eb-9cdc-2a8c355161a0.png)

## Dropdown list + hover
![image](https://user-images.githubusercontent.com/74857860/105923958-97252e80-603d-11eb-9fb0-9bf4eda6f234.png)

## People
![image](https://user-images.githubusercontent.com/74857860/105923983-a906d180-603d-11eb-99de-054ffab4394e.png)

## Dwarfs
![image](https://user-images.githubusercontent.com/74857860/105924002-b4f29380-603d-11eb-9773-fe3ae338d257.png)

2021-01-27 00:24 UTC, pdybowski requested changes
Fix Google fonts

2021-01-27 00:24 UTC, pdybowski commented on src/assets/fonts/google-fonts.css
> +@import url('https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap');
Wejdx ten link, skopiuj keto zawartosc i umiesc go zamiast Teton imports. Dzięki temu tekst będzie zmieniony nawet jak nie będzie połączenia z internetem

2021-01-27 11:19 UTC, hoolek77 approved these changes

2021-01-27 12:50 UTC, pdybowski approved these changes

2021-01-27 13:49 UTC, bartoszbialecki commented on src/app/screens/homepage/index.ts
> +  private changeButtonTextContext(value: string) {
Typo: TextContent

2021-01-27 13:52 UTC, bartoszbialecki approved these changes

2021-01-27 15:50 UTC, aleksandraj036 approved these changes

2021-01-27 18:51 UTC, merged