view info
pdybowski/village-defense pull request #45
Opened 2021-01-27 14:20 UTC by ibednorz

simple info view, mobile view to improve, but we need to determine what about the popup - we increase it permanently or add classes that will modify it

2021-01-27 16:58 UTC, bartoszbialecki commented on src/app/app.ts
> +    new infoContentProvider()
Why is it initialized here? I think it belongs to start page so it should be used there.

2021-01-27 16:59 UTC, bartoszbialecki commented on src/app/components/info/index.ts
> +const btn = document.querySelector('#info-button')
Maybe move it to the constructor?

2021-01-27 17:58 UTC, pdybowski requested changes

2021-01-27 17:58 UTC, pdybowski commented on src/app/app.ts
> +import infoContentProvider from './components/info'
Just components

2021-01-27 18:34 UTC, pdybowski commented on src/app/components/info/index.ts
> +  render() {
check private

2021-01-27 23:10 UTC, pdybowski requested changes
I will clean this code later. Make first letter of a class name to uppercase

2021-01-27 23:10 UTC, pdybowski commented on src/app/components/info/index.ts
> +export class infoContentProvider {
First letter should be uppercase in classes

2021-01-27 23:10 UTC, pdybowski commented on src/app/screens/homepage/index.ts
> +    new infoContentProvider()
First letter - uppercase

2021-01-27 23:10 UTC, pdybowski commented on src/app/screens/homepage/index.ts
> +import {infoContentProvider} from '../../components'
First letter uppercase

2021-01-27 23:16 UTC, pdybowski approved these changes

2021-01-27 23:34 UTC, pdybowski approved these changes

2021-01-27 23:56 UTC, hoolek77 approved these changes

2021-01-28 09:54 UTC, aleksandraj036 approved these changes

2021-01-28 11:11 UTC, merged