add method that will create html element
pdybowski/village-defense pull request #46
Opened 2021-01-27 15:04 UTC by ibednorz

mistake again, I typed fit add . and files from ib-9 are added. Only the interface and createElement function have been added

planned extension - properties and iteration over it

2021-01-27 16:51 UTC, bartoszbialecki commented on src/app/interfaces/elementConfig.ts
> +export interface elementConfig {
Name should be in PascalCase - ElementConfig

2021-01-27 16:53 UTC, bartoszbialecki commented on src/app/utils/createElement.ts
> +      element.className += `${className} `
It's ok, but you can also do: element.classList.add(className)

2021-01-27 16:55 UTC, bartoszbialecki commented on src/app/utils/createElement.ts
> +  }
What if I would like to add more event listeners? Maybe you can use here an array?

2021-01-27 16:55 UTC, bartoszbialecki commented on src/app/utils/createElement.ts
> +  styles,
styles is not used in the function body

2021-01-27 18:00 UTC, pdybowski approved these changes

2021-01-27 18:25 UTC, hoolek77 approved these changes

2021-01-27 18:31 UTC, pdybowski reviewed
add styles

2021-01-27 19:22 UTC, pdybowski requested changes
comment

2021-01-27 22:58 UTC, pdybowski requested changes
Just few things

2021-01-27 22:58 UTC, pdybowski commented on src/app/interfaces/elementConfig.ts
> +export interface ElementConfig {
Change name to customHtmlElement

2021-01-27 22:58 UTC, pdybowski commented on src/app/utils/createElement.ts
> +import { ElementConfig } from '../interfaces/elementConfig'
From 'interfaces'

In interfaces folder add index.ts and inside index.ts add export * from customHtmlElement

2021-01-27 23:33 UTC, pdybowski commented on src/app/components/info/index.ts
> +import { createElement } from '../../utils/createElement'
Just from utils

2021-01-27 23:38 UTC, pdybowski approved these changes

2021-01-28 09:53 UTC, aleksandraj036 approved these changes

2021-01-28 11:06 UTC, merged