Progress bar #14
pdybowski/village-defense pull request #64
Opened 2021-01-28 21:21 UTC by aleksandraj036

2021-01-28 21:51 UTC, bartoszbialecki requested changes
You should first pull changes on master branch and then merge them in your branch because there are many changes there.

2021-01-29 00:12 UTC, pdybowski requested changes
Use string interpolation
Add new file with bootstrap content
Remove scripts from index.html webpack does it for us

2021-01-29 00:12 UTC, pdybowski commented on src/app/screens/gamepage/index.ts
> +      this.progressBar.style.width = ( timeToNextWave *100 /30).toString() + "%";
const width = timeToNextWave * 100 / 30
this.progressBar.style.width = `${width}%`

Should work firn

2021-01-29 00:12 UTC, pdybowski commented on src/assets/css/screens/gameScreen.css
> +@import url(https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css);
Copy content of this url.
Create bootstrap.min.css in assets/css and paste url content there
Import this file in core/bootstrap.ts

2021-01-29 00:12 UTC, pdybowski commented on src/index.html
> +    <script src="app/screens/gamepage/index.ts"></script>
Remove it

2021-01-29 00:12 UTC, pdybowski commented on src/index.html
> +    <script src="app/game.ts"></script>
Remove it

2021-01-29 00:12 UTC, pdybowski commented on src/index.html
> +    <script src="app/screens/homepage/index.ts"></script>
Remove it

2021-01-29 21:06 UTC, pdybowski requested changes
We don't want to have external url calls

2021-01-29 21:06 UTC, pdybowski commented on src/assets/css/bootstrap.min.css
> +@import url(https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css);
Copy this url. 
Paste it in a browser 
Copy content of what will be displayed there
Paste it in this file instead of this import

2021-01-29 22:58 UTC, pdybowski approved these changes

2021-01-29 23:58 UTC, hoolek77 approved these changes

2021-01-30 00:11 UTC, merged