Settings popup
pdybowski/village-defense pull request #73
Opened 2021-01-30 12:51 UTC by hoolek77

- changing volume
- changing game difficulty
- if the user doesn't save and will close the popup by clicking overlay, all the settings will go to the state that they were before

2021-01-30 13:29 UTC, pdybowski reviewed
one thing to change for sure (import) 
This PR go after [https://github.com/pdybowski/village-defense/pull/70](url)

2021-01-30 13:29 UTC, pdybowski commented on src/app/screens/homepage/index.ts
> +import { GameSettingsView } from '../../components/'
it can be add one line above where InfoContentProvider is being imported

2021-01-30 23:04 UTC, pdybowski requested changes

2021-01-30 23:04 UTC, pdybowski commented on src/app/components/gameSettingsView.ts
> +import { playAudio } from '../utils'
We can remove it. We are using Audio class to play music

2021-01-30 23:04 UTC, pdybowski commented on src/app/screens/homepage/index.ts
> +    new GameSettingsView(this.app, new Audio())
Create in this folder this.audio = new Audio() and then pass it to settingsView. Audio is Application feature not only SettingsView

2021-01-31 00:00 UTC, pdybowski requested changes
Domy create new object. We will lose ability to handle the same state in different places of na app. We want to just one instance of audio object in whole application

2021-01-31 00:00 UTC, pdybowski commented on src/app/screens/homepage/index.ts
> +    this.audio = new Audio()
Nah domy create new Audio()
This.app should have audio. We Pass it in app.ts using this as na argument

Instead of creating new object just use: this.app.audio

Conclusion:
This.audio = this.app.audio

2021-01-31 00:10 UTC, pdybowski approved these changes

2021-01-31 09:57 UTC, bartoszbialecki approved these changes

2021-01-31 11:47 UTC, merged