Add game messages
pdybowski/village-defense pull request #92
Opened 2021-02-02 21:11 UTC by bartoszbialecki

2021-02-02 21:20 UTC, pdybowski commented on src/app/game.ts
> +      'Welcome! Start managing your village and protect it from invaders.'
invaders - nasty goblins

2021-02-02 21:47 UTC, pdybowski requested changes
there is no scroll bar

![image](https://user-images.githubusercontent.com/38506213/106666945-8aa65600-65a8-11eb-8c5d-c2eac33b4272.png)

2021-02-02 22:54 UTC, pdybowski approved these changes

2021-02-03 11:49 UTC, hoolek77 approved these changes

2021-02-03 11:50 UTC, merged