grid to flex on gamepage
pdybowski/village-defense pull request #96
Opened 2021-02-03 11:00 UTC by pdybowski

2021-02-03 21:49 UTC, bartoszbialecki requested changes
Please combine with current master changes.

2021-02-05 20:49 UTC, bartoszbialecki commented on src/app/components/gameSettingsModal.ts
> +        (If you want to listean to background music, you need to enable audio in the site preferences!)
typo: listen

2021-02-05 20:52 UTC, bartoszbialecki commented on src/assets/css/components/units.css
> +  height: 100%:
should be semicolon

2021-02-06 00:51 UTC, hoolek77 commented
In my opinion game page should have a max-height of 100vh, but we can discuss it in Monday

2021-02-09 19:08 UTC, closed without merging